/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.Color;
/**
 *
 * @author M VARREL MAULANA R
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Color DefaultColor,ClickedColor;
    
    public Dashboard() {
        initComponents();
        DefaultColor=new Color(255,193,42);
        ClickedColor=new Color(255, 223, 136);
        
        
        Barang.setBackground(DefaultColor);
        Penjualan.setBackground(DefaultColor);
        Laporan.setBackground(DefaultColor);
        Logout.setBackground(DefaultColor);
        getContentPane().setBackground(Color.WHITE); // ini penting
    jPanel1.setBackground(Color.WHITE); // kalau kamu pakai panel
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logout = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Laporan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Penjualan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Barang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPanel = new javax.swing.JDesktopPane();
        MenuName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logout.setBackground(new java.awt.Color(255, 193, 42));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogoutMousePressed(evt);
            }
        });

        jLabel5.setText("Logout");

        javax.swing.GroupLayout LogoutLayout = new javax.swing.GroupLayout(Logout);
        Logout.setLayout(LogoutLayout);
        LogoutLayout.setHorizontalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel5)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        LogoutLayout.setVerticalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 720, -1, -1));

        Laporan.setBackground(new java.awt.Color(255, 193, 42));
        Laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LaporanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LaporanMousePressed(evt);
            }
        });

        jLabel4.setText("Laporan");

        javax.swing.GroupLayout LaporanLayout = new javax.swing.GroupLayout(Laporan);
        Laporan.setLayout(LaporanLayout);
        LaporanLayout.setHorizontalGroup(
            LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LaporanLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel4)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        LaporanLayout.setVerticalGroup(
            LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LaporanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(Laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 220, 60));

        Penjualan.setBackground(new java.awt.Color(255, 193, 42));
        Penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PenjualanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PenjualanMousePressed(evt);
            }
        });

        jLabel3.setText("Penjualan");

        javax.swing.GroupLayout PenjualanLayout = new javax.swing.GroupLayout(Penjualan);
        Penjualan.setLayout(PenjualanLayout);
        PenjualanLayout.setHorizontalGroup(
            PenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PenjualanLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel3)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        PenjualanLayout.setVerticalGroup(
            PenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PenjualanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(Penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 220, -1));

        Barang.setBackground(new java.awt.Color(255, 193, 42));
        Barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarangMousePressed(evt);
            }
        });

        jLabel2.setText("Barang");

        javax.swing.GroupLayout BarangLayout = new javax.swing.GroupLayout(Barang);
        Barang.setLayout(BarangLayout);
        BarangLayout.setHorizontalGroup(
            BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarangLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel2)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        BarangLayout.setVerticalGroup(
            BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarangLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(Barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 220, 60));

        jDesktopPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPanelLayout = new javax.swing.GroupLayout(jDesktopPanel);
        jDesktopPanel.setLayout(jDesktopPanelLayout);
        jDesktopPanelLayout.setHorizontalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jDesktopPanelLayout.setVerticalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 820, 690));

        MenuName.setForeground(new java.awt.Color(255, 255, 255));
        MenuName.setText("Menu name");
        jPanel1.add(MenuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vector/mentahan.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BarangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarangMousePressed
        Barang.setBackground(ClickedColor);
        Penjualan.setBackground(DefaultColor);
        Laporan.setBackground(DefaultColor);
        Logout.setBackground(DefaultColor);
        
        MenuName.setText("Menu Barang");
    }//GEN-LAST:event_BarangMousePressed

    private void PenjualanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PenjualanMousePressed
        Barang.setBackground(DefaultColor);
        Penjualan.setBackground(ClickedColor);
        Laporan.setBackground(DefaultColor);
        Logout.setBackground(DefaultColor);
        
        MenuName.setText("Menu Penjualan");
    }//GEN-LAST:event_PenjualanMousePressed

    private void LaporanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaporanMousePressed
        Barang.setBackground(DefaultColor);
        Penjualan.setBackground(DefaultColor);
        Laporan.setBackground(ClickedColor);
        Logout.setBackground(DefaultColor);
        
        MenuName.setText("Menu Laporan");
    }//GEN-LAST:event_LaporanMousePressed

    private void LogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMousePressed
        Barang.setBackground(DefaultColor);
        Penjualan.setBackground(DefaultColor);
        Laporan.setBackground(DefaultColor);
        Logout.setBackground(ClickedColor);
        
    }//GEN-LAST:event_LogoutMousePressed

    private void BarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarangMouseClicked
        MenuBarang Barang=new MenuBarang();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(Barang).setVisible(true);
    }//GEN-LAST:event_BarangMouseClicked

    private void PenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PenjualanMouseClicked
        MenuPenjualan Penjualan=new MenuPenjualan();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(Penjualan).setVisible(true);
    }//GEN-LAST:event_PenjualanMouseClicked

    private void LaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaporanMouseClicked
        MenuLaporan Laporan=new MenuLaporan();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(Laporan).setVisible(true);
    }//GEN-LAST:event_LaporanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barang;
    private javax.swing.JPanel Laporan;
    private javax.swing.JPanel Logout;
    private javax.swing.JLabel MenuName;
    private javax.swing.JPanel Penjualan;
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
