/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import com.mysql.cj.xdevapi.Statement;
import java.awt.Color;
import java.math.BigDecimal;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;





/**
 *
 * @author M VARREL MAULANA R
 */
public class MenuPenjualan extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuBarang
     */
    public MenuPenjualan() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        getContentPane().setBackground(Color.WHITE); // ini penting
        loadTablePenjualan(); // <--- Tambahin ini
        
        
        bayar.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            try {
                int total = Integer.parseInt(harga_total.getText());
                int bayarVal = Integer.parseInt(bayar.getText());
                int kembali = bayarVal - total;
                kembalian.setText(String.valueOf(kembali));
            } catch (NumberFormatException e) {
                kembalian.setText("0");
            }
        }
    });
    }
    
    private void tambahBarangKeTabel(String kodeBarcode) {
    try {
        Connection conn = Koneksi.getConnection();
        String sql = "SELECT id_barang, nama, harga FROM barang WHERE barcode = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, kodeBarcode);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            int idBarang = rs.getInt("id_barang");
            String namaBarang = rs.getString("nama");
            int harga = rs.getInt("harga");
            int jumlah = 1;
            int total = harga * jumlah;

            // Tambahkan ke JTable
            DefaultTableModel model = (DefaultTableModel) tabel_penjualan.getModel();
            model.addRow(new Object[] { idBarang, namaBarang, harga, jumlah, total });

        } else {
            JOptionPane.showMessageDialog(this, "Barang dengan barcode ini tidak ditemukan.");
        }

        rs.close();
        pst.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}



    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_penjualan = new Palette.JTable_Custom();
        tambah = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        harga_total = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        simpan = new Palette.Custom_ButtonRounded();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Menu Penjualan");

        search.setText("Search..");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        tabel_penjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode", "Nama", "Harga", "Jumlah", "Total_Harga", "Kasir"
            }
        ));
        jScrollPane1.setViewportView(tabel_penjualan);

        tambah.setBackground(new java.awt.Color(114, 237, 107));
        tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahMouseClicked(evt);
            }
        });

        jLabel2.setText("Tambah");

        javax.swing.GroupLayout tambahLayout = new javax.swing.GroupLayout(tambah);
        tambah.setLayout(tambahLayout);
        tambahLayout.setHorizontalGroup(
            tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        tambahLayout.setVerticalGroup(
            tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jLabel3.setText("Harga total");

        jLabel4.setText("Bayar");

        jLabel5.setText("Kembali");

        kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianActionPerformed(evt);
            }
        });

        simpan.setText("simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(harga_total, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(search)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(517, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(simpan, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(harga_total, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(bayar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kembalian, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(481, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseClicked
            // Mengambil parent JDesktopPane
    javax.swing.JDesktopPane desktopPane = getDesktopPane();

    if (desktopPane != null) {
        // Menutup internal frame saat ini
        this.dispose();

        // Membuka internal frame baru (misalnya TambahBarang)
        Menutambahpenjualan tambahpenjualanFrame = new Menutambahpenjualan();
        desktopPane.add(tambahpenjualanFrame);
        tambahpenjualanFrame.setVisible(true);
    }
    }//GEN-LAST:event_tambahMouseClicked

    private void kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalianActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafetaria", "root", "");

        // 1. Simpan ke tabel detail_transaksi dan ambil id_detail
        String sqlDetail = "INSERT INTO detail_transaksi (tanggal, bayar, kembali) VALUES (?, ?, ?)";
        PreparedStatement pstDetail = conn.prepareStatement(sqlDetail, PreparedStatement.RETURN_GENERATED_KEYS);
        
        LocalDateTime now = LocalDateTime.now();
        pstDetail.setTimestamp(1, Timestamp.valueOf(now));
        pstDetail.setBigDecimal(2, new BigDecimal(bayar.getText()));
        pstDetail.setBigDecimal(3, new BigDecimal(kembalian.getText()));
        pstDetail.executeUpdate();
        
        ResultSet rs = pstDetail.getGeneratedKeys();
        int idDetail = 0;
        if (rs.next()) {
            idDetail = rs.getInt(1); // ✅ Dapatkan id_detail terbaru
        }

        // 2. Simpan detail barang ke tabel penjualan
        String sqlPenjualan = "INSERT INTO penjualan (id_barang, id_user, jumlah, total_harga, id_detail) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement pstItem = conn.prepareStatement(sqlPenjualan);

        for (int i = 0; i < tabel_penjualan.getRowCount(); i++) {
            String kodeBarang = tabel_penjualan.getValueAt(i, 1).toString();
            int idBarang = getIdBarangFromKode(kodeBarang, conn);
            int jumlah = Integer.parseInt(tabel_penjualan.getValueAt(i, 4).toString());
            int total = Integer.parseInt(tabel_penjualan.getValueAt(i, 5).toString());
            int idUser = 1; // Ganti sesuai user login jika dinamis

            pstItem.setInt(1, idBarang);
            pstItem.setInt(2, idUser);
            pstItem.setInt(3, jumlah);
            pstItem.setInt(4, total);
            pstItem.setInt(5, idDetail);
            pstItem.addBatch();
        }

        pstItem.executeBatch();
        pstItem.close();
        pstDetail.close();

        // 3. Hapus data penjualan yang tidak punya id_detail
        String sqlDeleteNull = "DELETE FROM penjualan WHERE id_detail IS NULL";
        PreparedStatement pstDelete = conn.prepareStatement(sqlDeleteNull);
        pstDelete.executeUpdate();
        pstDelete.close();

        JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan!");

        // 4. Kirim parameter id_detail ke JasperReport
        try {
            String path = "src/Report/reportpenjualan.jasper";
            Map<String, Object> parameter = new HashMap<>();
            parameter.put("id_detail", idDetail); // ✅ Kirim id_detail yang terbaru

            JasperPrint print = JasperFillManager.fillReport(path, parameter, conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menampilkan report: " + e.getMessage());
            e.printStackTrace();
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }
    }//GEN-LAST:event_simpanActionPerformed

    private int getLoggedInUserId() {
    // misal ambil dari sesi, session, atau variabel global
    return 1; // dummy user id
}
    
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void hitungTotalHargaSemua() {
    DefaultTableModel model = (DefaultTableModel) tabel_penjualan.getModel();
    int total = 0;
    for (int i = 0; i < model.getRowCount(); i++) {
        int nilai = Integer.parseInt(model.getValueAt(i, 5).toString()); // kolom Total_Harga
        total += nilai;
    }
    harga_total.setText(String.valueOf(total));
}

    
    private void loadTablePenjualan() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("Kode");
    model.addColumn("Nama");
    model.addColumn("Harga");
    model.addColumn("Jumlah");
    model.addColumn("Total_Harga");
    model.addColumn("Kasir");
    
    try {
        int no = 1;
        Connection conn = Koneksi.getConnection();
        String sql = "SELECT b.kode, b.nama, b.harga, p.jumlah, p.total_harga, u.username " +
             "FROM penjualan p " +
             "INNER JOIN barang b ON p.id_barang = b.id_barang " +
             "INNER JOIN user u ON p.id_user = u.id_user " +
             "WHERE p.id_detail IS NULL";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        
        while (rs.next()) {
            System.out.println("Data: " + rs.getString("kode")); // debug
            model.addRow(new Object[]{
                no++,
                rs.getString("kode"),
                rs.getString("nama"),
                rs.getInt("harga"),
                rs.getInt("jumlah"),
                rs.getInt("total_harga"),
                rs.getString("username")
            });
        }
        
        tabel_penjualan.setModel(model);
        
        // Center semua isi kolom di JTable
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);

        for (int i = 0; i < tabel_penjualan.getColumnCount(); i++) {
            tabel_penjualan.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        
        rs.close();
        pst.close();
        
        hitungTotalHargaSemua();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
        e.printStackTrace();
    }
    }
    
    private int getIdBarangFromKode(String kode, Connection conn) throws SQLException {
    String sql = "SELECT id_barang FROM barang WHERE kode = ?";
    PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, kode);
    ResultSet rs = pst.executeQuery();
    if (rs.next()) {
        return rs.getInt("id_barang");
    } else {
        throw new SQLException("Kode barang tidak ditemukan: " + kode);
    }
}

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private javax.swing.JTextField harga_total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField search;
    private Palette.Custom_ButtonRounded simpan;
    private Palette.JTable_Custom tabel_penjualan;
    private javax.swing.JPanel tambah;
    // End of variables declaration//GEN-END:variables
class Koneksi {
    private static Connection conn;

    public static Connection getConnection() {
        try {
            if (conn == null || conn.isClosed()) {
                String url = "jdbc:mysql://localhost:3306/cafetaria"; // <-- ganti nama_database
                String user = "root"; // username MySQL kamu
                String password = ""; // password MySQL kamu (kosongin kalau memang kosong)

                conn = DriverManager.getConnection(url, user, password);
                System.out.println("Koneksi Berhasil!");
            }
        } catch (SQLException e) {
            System.out.println("Koneksi Gagal! " + e.getMessage());
        }
        return conn;
    }
}
}
