/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import base.LoginMenu;

/**
 *
 * @author LAPTOP WA
 */
public class ResetPass extends javax.swing.JFrame {
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    public String user;

    /**
     * Creates new form ResetPass
     */
    public ResetPass() {
        initComponents();
        connectDatabase();
    }
    
    public ResetPass(String userOrEmail){
        this.user=userOrEmail;
         initComponents();
         connectDatabase();
    }
    
    private void connectDatabase() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafetaria", "root", "");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal terhubung ke database: " + ex.getMessage());
        }
    }
    
    private String hashPassword(String password) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] hashedBytes = md.digest(password.getBytes(StandardCharsets.UTF_8));
            StringBuilder sb = new StringBuilder();
            for (byte b : hashedBytes) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            JOptionPane.showMessageDialog(this, "Error hashing password: " + e.getMessage());
            return null;
        }
    }
    
    private void closeDatabaseConnection() {
        try {
            if (pst != null) pst.close();
            if (con != null) con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menutup koneksi database: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRessPass = new javax.swing.JTextField();
        txtVerRessPass = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRessPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRessPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtRessPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 340, 20));

        txtVerRessPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVerRessPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtVerRessPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 457, 340, -1));

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vector/btn cnfrmPass.png"))); // NOI18N
        btnReset.setBorder(null);
        btnReset.setContentAreaFilled(false);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vector/Hal CnfrmPass.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVerRessPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVerRessPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVerRessPassActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        String newPassword = txtRessPass.getText();
        String verifyPassword = txtVerRessPass.getText();
        
        if (newPassword.isEmpty() || verifyPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!newPassword.equals(verifyPassword)) {
            JOptionPane.showMessageDialog(this, "Password tidak cocok!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Proses update password
        updatePassword(newPassword);
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtRessPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRessPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRessPassActionPerformed

    private void updatePassword(String newPassword) {
        if (con == null) {
        JOptionPane.showMessageDialog(this, "Koneksi database gagal!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
        if (user == null || user.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Kesalahan: User tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        String hashedPassword = hashPassword(newPassword); // Hash password sebelum disimpan
        String query = "UPDATE user SET password = ? WHERE username = ? OR email = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, hashedPassword);
        pst.setString(2, user);
        pst.setString(3, user);
        

        int rowsUpdated = pst.executeUpdate();
        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(this, "Password berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            
            LoginMenu loginForm = new LoginMenu(); // Ganti dengan nama class login Anda
            loginForm.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui password! Pastikan username/email benar.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        pst.close();
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat update password: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtRessPass;
    private javax.swing.JTextField txtVerRessPass;
    // End of variables declaration//GEN-END:variables
}
