/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

import javax.swing.ImageIcon;
import java.net.URL;
import com.mysql.cj.x.protobuf.MysqlxSession.Reset;
import java.awt.HeadlessException;
//import java.net.PasswordAuthentication;
//import java.net.PasswordAuthentication
import base.ResetPass;
import java.util.Random;
import javax.mail.Session;
import java.util.Properties;
import javax.mail.*;
import javax.mail.internet.*;
import javax.swing.JOptionPane;

/**
 *
 * @author LAPTOP WA
 */
public class SendCode extends javax.swing.JFrame {
    int randomCode;
    
    
      private ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = getClass().getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            // Kembalikan icon kosong atau default
            return new ImageIcon(); 
        }
    }

    /**
     * Creates new form SendCode
     */
    public SendCode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmail = new javax.swing.JTextField();
        txtVer = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setBorder(null);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 330, 30));

        txtVer.setBorder(null);
        getContentPane().add(txtVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 330, 30));

        btnSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vector/Btn Send.png"))); // NOI18N
        btnSend.setBorder(null);
        btnSend.setContentAreaFilled(false);
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 60, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vector/btn Ver.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vector/Hal Send.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

         try {
             int enteredCode = Integer.parseInt(txtVer.getText());
    if (enteredCode == randomCode) {
         if (!txtEmail.getText().isEmpty()) { // Cek apakah txtEmail tidak null
              String userEmail = txtEmail.getText().trim();
            ResetPass rs = new ResetPass(userEmail); 
            rs.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Error: Email tidak boleh kosong.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Kode yang dimasukkan salah, silakan coba lagi.");
    }
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(null, "Format kode tidak valid, harap masukkan angka saja.");
}


    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
    String email = txtEmail.getText().trim();

    if (email.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Harap masukkan email terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (!isValidEmail(email)) {
        JOptionPane.showMessageDialog(this, "Format email tidak valid!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    randomCode = generateOTP(); // Simpan kode OTP ke variabel global
    boolean emailSent = sendEmail(email, randomCode);

    if (emailSent) {
        JOptionPane.showMessageDialog(this, "OTP telah dikirim ke email Anda.");
        txtVer.setEnabled(true); // Aktifkan input OTP
    } else {
        JOptionPane.showMessageDialog(this, "Gagal mengirim OTP. Silakan coba lagi.", "Error", JOptionPane.ERROR_MESSAGE);
    }
} 
private int generateOTP() {
    Random rand = new Random();
    return 100000 + rand.nextInt(900000);
}

private boolean isValidEmail(String email) {
    return email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$");
}

private boolean sendEmail(String to, int otpCode) {
    final String user = "refangga1952@gmail.com";
    final String pass = "tjygncgtjayunjgl"; 
    String subject = "Kode OTP Reset Password";
    String message = "Kode OTP Anda adalah: " + otpCode;

    Properties props = new Properties();
    props.put("mail.smtp.auth", "true");
    props.put("mail.smtp.starttls.enable", "true"); // Wajib diaktifkan
    props.put("mail.smtp.starttls.required", "true"); // Tambahkan ini
    props.put("mail.smtp.host", "smtp.gmail.com");
    props.put("mail.smtp.port", "587"); // Port untuk TLS
    props.put("mail.smtp.ssl.protocols", "TLSv1.2"); // Tambahkan protocol

     try {
        Session session = Session.getInstance(props,
            new javax.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(user, pass);
                }
            });

        Message msg = new MimeMessage(session); // Ubah nama variabel dari message ke msg
        msg.setFrom(new InternetAddress(user));
        msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
        msg.setSubject("Kode OTP Reset Password");
        msg.setText("Kode OTP Anda adalah: " + otpCode);

        Transport.send(msg);
        return true;
    } catch (MessagingException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, 
            "Gagal mengirim email. Error: " + e.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }


    }//GEN-LAST:event_btnSendActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendCode().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtVer;
    // End of variables declaration//GEN-END:variables
}
